blueprints/manager.py
from flask import Blueprint, flash, url_for, render_template, session, request, redirect, current_app
from util.util import login_required, manager_required, allowed_file, updatePromotionStatus, changePasswordFunction, level_two_required, sendMessage
from app import *
import db.queryStrings as QUERY
import db.db as db
import re
import os
from werkzeug.utils import secure_filename
import uuid
from datetime import date

manager_bp = Blueprint('manager',__name__,template_folder='templates',static_folder='static', static_url_path='/blueprints/static/')


# Manager Dashboard

@manager_bp.route('/manager', methods =  ['GET', 'POST'])
@manager_required
def manager_dashboard():
    customer_count = db.queryOneResult(QUERY.CUSTOMER_COUNT)['count(user_id)']
    this_month_order_count = db.queryOneResult(QUERY.CURRENT_MONTH_ORDERS_COUNT)['current_month_orders']
    last_month_order_count = db.queryOneResult(QUERY.LAST_MONTH_ORDERS_COUNT)['previous_month_orders']
    new_message_count = db.queryOneResult(QUERY.NEW_MESSAGE_COUNT)['count(message_id)']
    new_application_count = db.queryOneResult(QUERY.NEW_APPLICATION_COUNT)['application_count']

    if request.method == 'POST':

        user_id = request.form.get('user_id')
        message_subject = 'Payment overdue'
        orders = db.query(QUERY.GET_CUSTOMER_OVERDUE_ORDERS.format(user_id))
        message_content = 'You have overdue orders, including:'
        for o in orders:
            message_content += 'Order ID: ' + str(o['order_id']) + ', Ordered on: ' + o['order_date'].strftime('%d/%m/%Y') + ', Amount: $' + str(o['total_amount'])

        sendMessage(user_id, message_subject, message_content)
        flash('Reminder sent!', 'success')
            
    payments = db.query(QUERY.GET_CUSTOMERS_OVERDUE_PAYMENT)
    product_sales_data = db.query(QUERY.PRODUCT_SALES_DATA)

    return render_template('manager/manager_dashboard.html',customer_count=customer_count, 
                           new_message_count=new_message_count, this_month_order_count=this_month_order_count, last_month_order_count=last_month_order_count, 
                           new_application_count=new_application_count, payments = payments,product_sales_data=product_sales_data)

# Manager Profile
@manager_bp.route('/manager/profile')
@manager_required
def manager_profile():
    profile = db.queryOneResult(QUERY.GET_MANAGER_PROFILE.format(session['user_id']))
    return render_template('manager/manager_profile.html', profile = profile)

@manager_bp.route('/manager/profile/edit', methods = ['GET', 'POST'])
@manager_required
def manager_profile_edit():
    firstName = request.form.get('firstName')
    lastName = request.form.get('lastName')
    phone = request.form.get('phone')
    if not firstName or not lastName or not phone:
        flash('Please fill in all of the fields.','warning')
        profile = {
            "first_name": firstName,
            "last_name": lastName,
            "phone": phone
        }
    else:
        db.query(QUERY.EDIT_MANAGER_PROFILE.format(firstName, lastName, phone ,session['user_id']))
        query = QUERY.GET_MANAGER_PROFILE.format(session['user_id'])
        profile = db.queryOneResult(query)
        session['first_name'] = firstName
        session['last_name'] = lastName
        flash('Profile updated sucssesfully.', 'success')
    return render_template('manager/manager_profile.html', profile = profile)

# Manager Users Management
@manager_bp.route('/manager/users_management', methods=['GET'])
@manager_required
def manager_users_management():
    query = QUERY.GET_ALL_CUSTOMERS
    customers = db.query(query)
    query = QUERY.GET_ALL_STAFF
    staff = db.query(query)
    return render_template('manager/manager_users_management.html', customers = customers, staff=staff)

# Add New User
@manager_bp.route('/manager/manager_add_new_user', methods=['GET','POST'])
@manager_required
def manager_add_new_user():
    if request.method == 'GET':
        return render_template('manager/manager_add_new_user.html')
    else:
        user_details = {
            'user_type': request.form.get('user_type'),
            'password': request.form.get('password'),  
            'first_name': request.form.get('first_name'),
            'last_name': request.form.get('last_name'),
            'phone': request.form.get('phone'),
            'email': request.form.get('email'),
        }
        account = db.queryOneResult(QUERY.FIND_A_USER_BY_EMAIL.format(user_details['email']))
        if account:
            flash('Account already exists!', 'warning')
            return redirect('/manager/users_management')
        password, salt = changePasswordFunction(user_details['password'])
        if user_details['user_type'] == 'customer':
            # Insert into users table
            id = db.querywithLastID(QUERY.REGISTER_A_NEW_USER.format(user_details['email'], password, salt ))
            # Insert into customers table
            db.query(QUERY.ADD_A_CUSTOMER.format(id,user_details['first_name'], user_details['last_name'], user_details['phone'] ))
            flash("Customer added successfully!", "success")
        elif user_details['user_type'] == 'staff':
            # Insert into users table
            id = db.querywithLastID(QUERY.REGISTER_A_NEW_USER_STAFF_TYPE.format(user_details['email'], password, salt,'staff' ))
            # Insert into staff table
            db.query(QUERY.ADD_A_STAFF.format(id,user_details['first_name'], user_details['last_name'], user_details['phone']))
            flash("Staff added successfully!", "success")
        return redirect('/manager/users_management')


#edit users
@manager_bp.route('/manager/users_management/editUser/<int:id>', methods=['GET'])
@manager_required
def manager_editUser(id):

    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))
    if not account or account['user_type'] == "manager" or account['user_type'] == "admin":
        flash("Unauthorized!", 'danger')
        return redirect('/manager/users_management')
    elif account['user_type'] == "customer":
        account = db.queryOneResult(QUERY.GET_CUSTOMER_DETAILS_BY_ID.format(id))
        return render_template('manager/manager_customer_profile.html', profile = account)
    elif account['user_type'] == "staff":
        account = db.queryOneResult(QUERY.GET_STAFF_DETAILS_BY_ID.format(id))
        return render_template('manager/manager_staff_profile.html', profile = account)
   

#edit users
@manager_bp.route('/manager/users_management/editUser/editUserDetails', methods=['POST'])
@manager_required
def manager_editUserDetails():
  
 
    id = request.form['id']
    firstName = request.form['firstName']
    lastName = request.form['lastName']
    phone = request.form['phone']
    email = request.form['email']

    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))

    if not firstName or not lastName or not phone:
        flash('Please fill in all of the fields.', 'warning')
        return redirect('/manager/users_management/editUser/' + id)

    if email != account['email_address']:
        db.queryOneResult(QUERY.UPDATE_USER_EMAIL_BY_ID.format(email, id))

    if account['user_type'] == "customer":
        db.queryOneResult(QUERY.UPDATE_CUSTOMER_DETAILS_BY_ID.format(firstName, lastName, phone, id))
    elif account['user_type'] == "staff":
        db.queryOneResult(QUERY.UPDATE_STAFF_DETAILS_BY_ID.format(firstName, lastName, phone, id))

    flash("User profile updated!", "success")
    return redirect('/manager/users_management/editUser/' + id)


# Deactivate a user
@manager_bp.route('/manager/users_management/deactiveUser/<int:id>')
@manager_required
def manager_deactiveUser(id):
    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))
   
    if not account or account['user_type'] == "manager" or account['user_type'] == "admin":
        flash("Unauthorized!", 'danger')
        return redirect('/manager/users_management')
    else:
        db.queryOneResult(QUERY.DEACTIVATE_USER_BY_ID.format(id))
        flash("User is deactivated!")
        return redirect('/manager/users_management')

# Activate a user
@manager_bp.route('/manager/users_management/activeUser/<int:id>')
@manager_required
def manager_activeUser(id):
    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))
    if not account or account['user_type'] == "manager" or account['user_type'] == "admin":
        flash("Unauthorized!", 'danger')
        return redirect('/manager/users_management')
    else:
        db.queryOneResult(QUERY.ACTIVATE_USER_BY_ID.format(id))
        flash("User is activated!", 'success')
        return redirect('/manager/users_management')


# Manager Promotion Management
@manager_bp.route('/promotion_management')
@level_two_required
def manager_promotion_management():
    updatePromotionStatus()
    promotions = db.query(QUERY.GET_PROMOTION_LIST.format())
    return render_template('manager/promotion_manage.html', promotions = promotions )

@manager_bp.route('/promotion_management/sort', methods=['POST'])
@level_two_required
def promotion_list_sorted():
    updatePromotionStatus()
    type = request.form.get('type')
    status = request.form.get('status')
    print(type, status)

    typeQ = f'promotion_type = "{type}"' if type else ''
    statusQ = f'status = "{status}"' if status else ''
    andQ = 'AND' if typeQ and statusQ else ''
    
    promotions = db.query(f'SELECT * FROM Promotions WHERE {typeQ} {andQ} {statusQ} ORDER BY promotion_id ASC;')
    return render_template('manager/promotion_manage.html', promotions = promotions, type = type, status = status)


@manager_bp.route('/promotion/<int:id>')
@level_two_required
def promotion_detail(id):
    updatePromotionStatus()
    promotion = db.queryOneResult(QUERY.GET_PROMOTION_DETAIL.format(id))
    categories = db.query(QUERY.GET_PROMOTION_CATAGORIES.format(id))
    subcategories = db.query(QUERY.GET_PROMOTION_SUBCATAGORIES.format(id))

templates/inventory/edit_discount.html
{% if session['user_type'] == 'staff' %}
    {% extends 'staff/staff_layout.html' %} 
{% elif session['user_type'] == 'manager' %}
    {% extends 'manager/manager_layout.html' %} 
{% elif session['user_type'] == 'admin' %}
    {% extends 'admin/admin_layout.html' %} 
{% endif %}

{% block title %} Moa Creek Rural Supplies {% endblock %}
{% block content %}
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Promotions</h1>
        <nav>
            <ol class="breadcrumb">
                {% set path = session.user_type ~ "." ~ session.user_type ~ "_dashboard" %}
                <li class="breadcrumb-item"><a href="{{ url_for(path) }}">Home</a></li>
                <li class="breadcrumb-item active">Everyday Discount</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->
    <section class="section profile">
        <div class="col">
            <div class="card">
                <div class="card-body pt-3">
                    <!-- Bordered Tabs -->
                    <div class="tab-content pt-2">
                        <!-- Promotion Overview -->
                        <div class="tab-pane fade show active profile-overview" id="promotion-overview">
                            <p class="small fst-italic">{{promotion.promotion_description}}</p>
                            <h5 class="card-title">{% set discount  = (promotion.discount_rate|float * 100) | int %}
                                <div class="row">
                                  <div class="col-lg-3 col-md-4 label ">Discount</div>
                                  <div class="col-lg-9 col-md-8"> {{ discount }}%</div>
                                </div></h5>
                           
                            <div class="row">
                                <div class="col-lg-3 col-md-4 label ">Discounted Products</div>
                                <div class="col-lg-9 col-md-8">
                                    <ul id="list" style="list-style-type:none;">
                                        {% for product in products %}
                                        <li id="list-{{ product.product_id }}">{{ product.product_id }} - {{product.product_name}}</li>
                                    {% endfor %}
                                    </ul>
                                    
                                </div>
                            </div>
                        </div><!-- End Promotion Overview -->
                        <!-- Promotion Edit -->
                        <div >
                            <form method="post" action="{{url_for('internal.editDiscount')}}">
                                <div class="row">
                                    <div class="col-lg-3 col-md-4 label">Categories</div>
                                    <div class="col-lg-9 col-md-8">
                                    <select name="categoryInput" onchange="this.form.submit()">
                                        <option value="">Select a category</option>
                                        {% for category in allCategories%}
                                            {% if categorySelected|int == category.category_id|int %}
                                                <option value="{{category.category_id}}" selected>
                                            {% else %}
                                                <option value="{{category.category_id}}">
                                            {% endif %}
                                                {{category.category_id}} {{category.category_name}}</option>
                                        {% endfor %}
                                    </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-3 col-md-4 label">Subcategories</div>
                                    <div class="col-lg-9 col-md-8">
                                        <select name="subcategoryInput" onchange="this.form.submit()">
                                            <option value="">Select a subcategory</option>
                                            {% for subcategory in allSubcategories%}
                                            {% if subcategorySelected|int == subcategory.subcategory_id|int %}
                                                <option value="{{subcategory.subcategory_id}}" selected>
                                            {% else %}
                                                <option value="{{subcategory.subcategory_id}}">
                                            {% endif %}
                                                {{subcategory.subcategory_id}} {{subcategory.subcategory_name}}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </form>
                           
                            <form method="POST" action="{{ url_for('internal.editDiscountAll') }}" >
                                <div class="row mb-3">
                                    <legend class="col-form-label col-sm-3 pt-0">Products</legend>
                                    <div class="col-sm-9">
                                        {% for product in allProducts %}
                                            <div class="form-check">
                                                <input class="form-check-input" name="itemsChecked" type="checkbox" value="{{product.product_id}}" id="box-{{product.product_id}}" {%if product.product_id in products|map(attribute='product_id')%}checked{%endif%} onchange="changeDiscountStatus({{product.product_id}}, '{{product.product_name}}')">
                                                <input hidden type="text" name="allItemsShown" value="{{product.product_id}}">
                                                <label class="form-check-label" for="{{product.product_id}}">
                                                    {{product.product_id}} - {{product.product_name}}
                                                </label>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                
                                <div class="text-center">
                                    <button type="submit" name="action" value="checkAll" class="btn btn-success">Check All</button>
                                    <button type="submit" name="action" value="uncheckAll" class="btn btn-warning">Uncheck All</button>
                                    {% if categorySelected or subcategorySelected %}
                                    <a href="{{url_for('internal.editDiscount')}}" class="ml-2 btn btn-secondary">Reset Filter</a>
                                    {% endif %}
                                </div>
                                
                            </form>
                        </div><!-- End Promotion Edit -->
                    </div><!-- End Bordered Tabs -->
                </div>
            </div>
        </div>
    </section>
</main><!-- End #main -->

]
<script src="{{url_for('static', filename='edit-discount.js')}}"></script>

{% endblock %}


    

templates/inventory/inventory_management.html
{% if session['user_type'] == 'staff' %}
{% extends 'staff/staff_layout.html' %} 
{% elif session['user_type'] == 'manager' %}
{% extends 'manager/manager_layout.html' %} 
{% elif session['user_type'] == 'admin' %}
{% extends 'admin/admin_layout.html' %} 
{% endif %}


{% block title %} Moa Creek Rural Supplies {% endblock %}
{% block css %}
<style>
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
</style>

{% endblock %}
{% block content %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>Inventory Management</h1>
      <nav>
        <ol class="breadcrumb">
          {% set path = session.user_type ~ "." ~ session.user_type ~ "_dashboard" %}
          <li class="breadcrumb-item"><a href="{{ url_for(path) }}">Home</a></li>
          <li class="breadcrumb-item active">Inventory Management</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
              <div class="card-body">
                  <!-- Bordered Tabs -->
                  <h5 class="card-title">Manage Inventory</h5>
  
                  <!-- Add Product Button -->
                  <div class="mb-3">
                      <a href="{{url_for('internal.addProduct')}}" class="btn btn-primary btn-sm">Add New Product</a>
                  </div>
                    <div class="table-responsive">
                        <table class="table table-hover datatable">
                            <thead>
                            <tr>
                                    <th>Product</th>
                                    <th>Category</th>
                                    <th>Subcategory</th>
                                    <th>Stock</th>
                                    <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                <tr>
                                  <td>
                                    {% if product.product_image_id %}
                                      <img src="/blueprints/static/product_image/{{ product.product_image }}" class="img-thumbnail" style="max-width: 50px; max-height: 50px;">
                                      {% else %}
                                      <img src="/blueprints/static/product_image/default-image.jpg" alt="Product" class="img-thumbnail" style="max-width: 50px; max-height: 50px;">
                                      {% endif %}
                                    <a href="{{ url_for('internal.product_detail', id=product.product_id) }}">{{ product.product_name }}
                                      
                                  </a></td>
                                  <td>{{ product.category_name }}</td>
                                  <td>{{ product.subcategory_name }}</td>
                                  <td>
                                      <form name="{{ product.product_id }}" action="{{ url_for('internal.inventory_list') }}" method="post" onsubmit="submitForm(event)">
                                          <input type="hidden" name="product_id" id="product_id" value="{{ product.product_id }}">
                                          <input type="number" name="stock_quantity" id="stock_quantity" value="{{ product.stock_quantity }}" onblur="this.form.submit();" style="width: 60px; text-align: center;">
                                      </form>
                                  </td>
                                  <td>{% if product.product_status %} Active {% else %} Inactive {% endif %}</td>
                              </tr>
                              
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                  </div>
              </div>
          </div>
      </div>
    </section>

</main><!-- End #main -->


{% endblock %}

templates/inventory/product_new.html
{% if session['user_type'] == 'staff' %}
{% extends 'staff/staff_layout.html' %} 
{% elif session['user_type'] == 'manager' %}
{% extends 'manager/manager_layout.html' %} 
{% elif session['user_type'] == 'admin' %}
{% extends 'admin/admin_layout.html' %} 
{% endif %}
{% block title %} Moa Creek Rural Supplies - New Product{% endblock %}
{% block content %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>New Product</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('manager.manager_dashboard') }}">Home</a></li>
          <li class="breadcrumb-item"><a href="{{url_for('internal.inventory_list')}}">Inventory</a></li>
          <li class="breadcrumb-item active">New Product</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
        <div class="col-xl-12">
          <form method="POST" enctype=multipart/form-data action="{{url_for('internal.addProduct', role = 'manager')}}" >
                <div class="card">
                  <div class="card-body pt-3">

                    <div class="row mb-3">
                      <label for="name" class="col-md-4 col-lg-3 col-form-label">Name</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="name" type="text" class="form-control" id="name" required>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="description" class="col-md-4 col-lg-3 col-form-label">Description</label>
                      <div class="col-md-8 col-lg-9">
                        <textarea name="description" class="form-control" id="description" rows="4" required></textarea>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="price" class="col-md-4 col-lg-3 col-form-label">Price</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="price" type="number" class="form-control" id="price" required step="0.01" min="0.00" max="9999.99">
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="category" class="col-md-4 col-lg-3 col-form-label">Category</label>
                      <div class="col-md-8 col-lg-9">
                        <select name="category" class="form-control" id="subcatSelector" onchange="updateSubcategory(event)" required>
                          <option selected disabled>Choose from below</option>
                          {% for category in allCategories %}
                            <option value="{{category.category_id}}">{{category.category_name}}</option>
                          {% endfor %}
                        </select>
                      </div>
                    </div>

                    <div class="row mb-3">
                        <label for="subcategory" class="col-md-4 col-lg-3 col-form-label">Subcategory</label>
                        <div class="col-md-8 col-lg-9">
                          <select name="subcategory" id="subcategory" class="form-control" required>
                          </select>
                        </div>
                    </div>

                    <div class="row mb-3">
                      <label for="quantity" class="col-md-4 col-lg-3 col-form-label">Quantity</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="quantity" type="number" step="1" class="form-control" id="quantity" value="1"   min="1"     required>
                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="oversized" class="col-md-4 col-lg-3 col-form-label">Oversized</label>
                      <div class="col-md-8 col-lg-9">
                       
                        <div class="row mb-3">
                          <input type="radio" name="oversized" class="col-lg-1" value="0" checked>
                          <label class="col-md-4" for="0">Standard</label>
                        </div>
                        <div class="row mb-3">
                          <input type="radio" name="oversized" class="col-lg-1" value="1">
                          <label class="col-md-4" for="1">Oversize</label>
                        </div>
                        <div class="row mb-3">
                          <input type="radio" name="oversized" class="col-lg-1" value="2" >
                          <label class="col-md-4" for="0">Too big, must pick-up</label>
                        </div>



                      </div>
                    </div>

                    <div class="row mb-3">
                      <label for="uploadInputFile" class="col-md-4 col-lg-3 col-form-label">Product Image</label>
                      <div class="col-md-8 col-lg-9">
                        <img class="img-fluid" src="#" alt="Image Preview" id="imagePreview" style="display:none; max-width: 20vw; max-height: 20vh;">
                        <div class="pt-2 row">
                            <input type="file" multiple name="uploadInputFile" id="uploadInputFile" class="col-md-6" onblur="getElementById('imagePreview').style.display = 'block';">
                            <button class="btn btn-danger btn-sm col-md-1" title="Remove my product image" onclick="getElementById('uploadInputFile').value = '';"><i class="bi bi-trash"></i></button>
                        </div>
                      </div>
                    </div>

                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </div>
          </form>
        </div>
    </section>

</main><!-- End #main -->


<script>
  async function updateSubcategory(event) {
    const selectedOption = event.target.value;

    const response = await fetch('/inventory/product/get-subcategory', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ selected_option: selectedOption }),
    });

    if (response.ok) {
        const options = await response.json();
        const subOptionsSelect = document.getElementById('subcategory');
        subOptionsSelect.innerHTML = '';

        options.forEach(option => {
            const optionElement = document.createElement('option');

            optionElement.value = option;
            optionElement.textContent = option;
            subOptionsSelect.appendChild(optionElement);
        });
    } else {
        alert('Failed to load options');
    }
  }
  uploadInputFile.onchange = evt => {
  const [file] = uploadInputFile.files
  if (file) {
    imagePreview.src = URL.createObjectURL(file)
  }
}
</script>

{% endblock %}