blueprints/common.py
from flask import Blueprint, flash,render_template,request,redirect, session,url_for, jsonify, current_app
from datetime import datetime, timedelta
import db.queryStrings as QUERY
import db.db as db
from util.util import login_required, checkPassword, uploadImage, changePasswordFunction, allowed_file, updatePromotionStatus, level_one_required, get_price_after_discount
import re
import os
from werkzeug.utils import secure_filename
import uuid


common_bp = Blueprint('common',__name__,template_folder='templates',static_folder='static', static_url_path='/blueprints/static/')

# Home Page
@common_bp.route('/')
@common_bp.route('/home')
def home():
    updatePromotionStatus()

    if 'loggedin' in session:
        if session['user_type'] == 'customer':
            return redirect(url_for('customer.customer_dashboard'))
    #     elif session['user_type'] == 'staff':
    #         return redirect(url_for('staff.staff_dashboard'))
    #     elif session['user_type'] == 'manager':
    #         return redirect(url_for('manager.manager_dashboard'))
    #     elif session['user_type'] == 'admin':
    #         return redirect(url_for('admin.admin_dashboard'))
    categories = db.query(QUERY.GET_ALL_CATEGORIES)
    subcategories = db.query(QUERY.GET_ALL_SUBCATEGORIES)
    promotions = db.query(QUERY.GET_PROMOTION_LIST)

    hot_products = db.query(QUERY.GET_HOT_PRODUCTS)
    news = db.query(QUERY.GET_ALL_NEWS)

    return render_template('home.html',  hot_products=hot_products, promotions=promotions, news=news,  categories = categories,subcategories = subcategories )

@common_bp.route('/<role>/password/update', methods = ['GET', 'POST'])
@login_required
def password_update(role):
    if request.method == 'POST':
        currentPassword = request.form.get('currentPassword')
        newPassword = request.form.get('newPassword')
        reNewPassword = request.form.get('reNewPassword')

        query = QUERY.GET_CURRENT_PASSWORD.format(session['user_id'])
        account = db.queryOneResult(query)

        # Check current password is correct
        if not checkPassword(account['password'], currentPassword, account['salt']):
            flash("The current password does not match.", 'warning')
        # Compare the two new password input
        elif newPassword != reNewPassword:
            flash("The new passwords do not match. Please try again.", 'warning')
        # Check password requirement
        elif not re.match(r'^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*\W).{8,}', newPassword):
            flash("The new password must contain at least 4 types and 8 characters.", 'warning')
        # Update Password
        else:
            password, salt = changePasswordFunction(newPassword)
            db.query(QUERY.UPDATE_PASSWORD.format(password, salt, session['user_id']))
            flash("Password updated.", 'success')

        path = f"{role}.{role}_profile"
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')

@common_bp.route('/<role>/profile/uploader', methods = ['GET', 'POST'])
@login_required
def profile_picture_upload(role):
    if request.method == 'POST':
        if 'image' not in request.files:
            flash('No file selected.')
            path = f"{role}.{role}_profile"
            return redirect(url_for(path))
        file = request.files['image']
        if file.filename == '':
            flash('No file uploaded.')
        elif file and allowed_file(file.filename):
            UPLOAD_FOLDER = 'static/profile_image'
            current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
            filename = secure_filename(file.filename)
            
            index = filename.rfind('.')
            substring = filename[index:]
            filename = uuid.uuid4().hex + substring

            basedir = os.path.abspath(os.path.dirname(__file__))
            filePath = basedir + "/" + UPLOAD_FOLDER
            if not os.path.exists(filePath):
                os.makedirs(filePath)
            file.save(os.path.join(basedir, UPLOAD_FOLDER, filename))

            # change blueprint name style to table name style
            roles = role
    
            if role == "staff": 
                roles = 'Staff'
            elif role == "customer": 
                roles = "Customers"
            elif role == "admin": 
                roles = "Admins"
            elif role == "manager": 
                roles = "Managers"

            db.query(QUERY.SET_PROFILE_IMAGE.format(roles, filename, session['user_id']))
            session['profile_image'] = filename
            flash('Image uploaded.', 'success')
        path = f"{role}.{role}_profile" 
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')

@common_bp.route('/<role>/profile/delete', methods = ['GET', 'POST'])
@login_required
def profile_picture_delete(role):
    if request.method == 'POST':
        query = QUERY.GET_PROFILE_IMAGE_PATH.format(session['user_id'])
        file = db.queryOneResult(query)
        try:
            UPLOAD_FOLDER = 'static/profile_image'
            current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
           

            basedir = os.path.abspath(os.path.dirname(__file__))
            filePath = basedir + "/" + UPLOAD_FOLDER
            if not os.path.exists(filePath):
                os.makedirs(filePath)
         
    
            os.remove(os.path.join(basedir, UPLOAD_FOLDER, file['profile_image']))

            # change blueprint name style to table name style
            roles = role
            if role == "staff": 
                roles = 'Staff'
            elif role == "customer": 
                roles = "Customers"
            elif role == "admin": 
                roles = "Admins"
            elif role == "manager": 
                roles = "Managers"


            db.query(QUERY.DELETE_PROFILE_IMAGE.format(roles, session['user_id']))
            flash("Profile image deleted.", 'success')
        except Exception as e:
            flash(f"Error in deleting files: {e}", 'danger')
        path = f"{role}.{role}_profile" 
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')
    


# Contact us Page
@common_bp.route('/contactus')
def contactUs():
    return render_template('contactUs.html')

blueprints/manager.py
from flask import Blueprint, flash, url_for, render_template, session, request, redirect, current_app
from util.util import login_required, manager_required, allowed_file, updatePromotionStatus, changePasswordFunction, level_two_required, sendMessage
from app import *
import db.queryStrings as QUERY
import db.db as db
import re
import os
from werkzeug.utils import secure_filename
import uuid
from datetime import date

manager_bp = Blueprint('manager',__name__,template_folder='templates',static_folder='static', static_url_path='/blueprints/static/')


# Manager Dashboard

@manager_bp.route('/manager', methods =  ['GET', 'POST'])
@manager_required
def manager_dashboard():
    customer_count = db.queryOneResult(QUERY.CUSTOMER_COUNT)['count(user_id)']
    this_month_order_count = db.queryOneResult(QUERY.CURRENT_MONTH_ORDERS_COUNT)['current_month_orders']
    last_month_order_count = db.queryOneResult(QUERY.LAST_MONTH_ORDERS_COUNT)['previous_month_orders']
    new_message_count = db.queryOneResult(QUERY.NEW_MESSAGE_COUNT)['count(message_id)']
    new_application_count = db.queryOneResult(QUERY.NEW_APPLICATION_COUNT)['application_count']

    if request.method == 'POST':

        user_id = request.form.get('user_id')
        message_subject = 'Payment overdue'
        orders = db.query(QUERY.GET_CUSTOMER_OVERDUE_ORDERS.format(user_id))
        message_content = 'You have overdue orders, including:'
        for o in orders:
            message_content += 'Order ID: ' + str(o['order_id']) + ', Ordered on: ' + o['order_date'].strftime('%d/%m/%Y') + ', Amount: $' + str(o['total_amount'])

        sendMessage(user_id, message_subject, message_content)
        flash('Reminder sent!', 'success')
            
    payments = db.query(QUERY.GET_CUSTOMERS_OVERDUE_PAYMENT)
    product_sales_data = db.query(QUERY.PRODUCT_SALES_DATA)

    return render_template('manager/manager_dashboard.html',customer_count=customer_count, 
                           new_message_count=new_message_count, this_month_order_count=this_month_order_count, last_month_order_count=last_month_order_count, 
                           new_application_count=new_application_count, payments = payments,product_sales_data=product_sales_data)

# Manager Profile
@manager_bp.route('/manager/profile')
@manager_required
def manager_profile():
    profile = db.queryOneResult(QUERY.GET_MANAGER_PROFILE.format(session['user_id']))
    return render_template('manager/manager_profile.html', profile = profile)

@manager_bp.route('/manager/profile/edit', methods = ['GET', 'POST'])
@manager_required
def manager_profile_edit():
    firstName = request.form.get('firstName')
    lastName = request.form.get('lastName')
    phone = request.form.get('phone')
    if not firstName or not lastName or not phone:
        flash('Please fill in all of the fields.','warning')
        profile = {
            "first_name": firstName,
            "last_name": lastName,
            "phone": phone
        }
    else:
        db.query(QUERY.EDIT_MANAGER_PROFILE.format(firstName, lastName, phone ,session['user_id']))
        query = QUERY.GET_MANAGER_PROFILE.format(session['user_id'])
        profile = db.queryOneResult(query)
        session['first_name'] = firstName
        session['last_name'] = lastName
        flash('Profile updated sucssesfully.', 'success')
    return render_template('manager/manager_profile.html', profile = profile)

# Manager Users Management
@manager_bp.route('/manager/users_management', methods=['GET'])
@manager_required
def manager_users_management():
    query = QUERY.GET_ALL_CUSTOMERS
    customers = db.query(query)
    query = QUERY.GET_ALL_STAFF
    staff = db.query(query)
    return render_template('manager/manager_users_management.html', customers = customers, staff=staff)

# Add New User
@manager_bp.route('/manager/manager_add_new_user', methods=['GET','POST'])
@manager_required
def manager_add_new_user():
    if request.method == 'GET':
        return render_template('manager/manager_add_new_user.html')
    else:
        user_details = {
            'user_type': request.form.get('user_type'),
            'password': request.form.get('password'),  
            'first_name': request.form.get('first_name'),
            'last_name': request.form.get('last_name'),
            'phone': request.form.get('phone'),
            'email': request.form.get('email'),
        }
        account = db.queryOneResult(QUERY.FIND_A_USER_BY_EMAIL.format(user_details['email']))
        if account:
            flash('Account already exists!', 'warning')
            return redirect('/manager/users_management')
        password, salt = changePasswordFunction(user_details['password'])
        if user_details['user_type'] == 'customer':
            # Insert into users table
            id = db.querywithLastID(QUERY.REGISTER_A_NEW_USER.format(user_details['email'], password, salt ))
            # Insert into customers table
            db.query(QUERY.ADD_A_CUSTOMER.format(id,user_details['first_name'], user_details['last_name'], user_details['phone'] ))
            flash("Customer added successfully!", "success")
        elif user_details['user_type'] == 'staff':
            # Insert into users table
            id = db.querywithLastID(QUERY.REGISTER_A_NEW_USER_STAFF_TYPE.format(user_details['email'], password, salt,'staff' ))
            # Insert into staff table
            db.query(QUERY.ADD_A_STAFF.format(id,user_details['first_name'], user_details['last_name'], user_details['phone']))
            flash("Staff added successfully!", "success")
        return redirect('/manager/users_management')


#edit users
@manager_bp.route('/manager/users_management/editUser/<int:id>', methods=['GET'])
@manager_required
def manager_editUser(id):

    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))
    if not account or account['user_type'] == "manager" or account['user_type'] == "admin":
        flash("Unauthorized!", 'danger')
        return redirect('/manager/users_management')
    elif account['user_type'] == "customer":
        account = db.queryOneResult(QUERY.GET_CUSTOMER_DETAILS_BY_ID.format(id))
        return render_template('manager/manager_customer_profile.html', profile = account)
    elif account['user_type'] == "staff":
        account = db.queryOneResult(QUERY.GET_STAFF_DETAILS_BY_ID.format(id))
        return render_template('manager/manager_staff_profile.html', profile = account)
   

#edit users
@manager_bp.route('/manager/users_management/editUser/editUserDetails', methods=['POST'])
@manager_required
def manager_editUserDetails():
  
 
    id = request.form['id']
    firstName = request.form['firstName']
    lastName = request.form['lastName']
    phone = request.form['phone']
    email = request.form['email']

    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))

    if not firstName or not lastName or not phone:
        flash('Please fill in all of the fields.', 'warning')
        return redirect('/manager/users_management/editUser/' + id)

    if email != account['email_address']:
        db.queryOneResult(QUERY.UPDATE_USER_EMAIL_BY_ID.format(email, id))

    if account['user_type'] == "customer":
        db.queryOneResult(QUERY.UPDATE_CUSTOMER_DETAILS_BY_ID.format(firstName, lastName, phone, id))
    elif account['user_type'] == "staff":
        db.queryOneResult(QUERY.UPDATE_STAFF_DETAILS_BY_ID.format(firstName, lastName, phone, id))

    flash("User profile updated!", "success")
    return redirect('/manager/users_management/editUser/' + id)


# Deactivate a user
@manager_bp.route('/manager/users_management/deactiveUser/<int:id>')
@manager_required
def manager_deactiveUser(id):
    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))
   
    if not account or account['user_type'] == "manager" or account['user_type'] == "admin":
        flash("Unauthorized!", 'danger')
        return redirect('/manager/users_management')
    else:
        db.queryOneResult(QUERY.DEACTIVATE_USER_BY_ID.format(id))
        flash("User is deactivated!")
        return redirect('/manager/users_management')

# Activate a user
@manager_bp.route('/manager/users_management/activeUser/<int:id>')
@manager_required
def manager_activeUser(id):
    account = db.queryOneResult(QUERY.FIND_A_USER_BY_ID.format(id))
    if not account or account['user_type'] == "manager" or account['user_type'] == "admin":
        flash("Unauthorized!", 'danger')
        return redirect('/manager/users_management')
    else:
        db.queryOneResult(QUERY.ACTIVATE_USER_BY_ID.format(id))
        flash("User is activated!", 'success')
        return redirect('/manager/users_management')


# Manager Promotion Management
@manager_bp.route('/promotion_management')
@level_two_required
def manager_promotion_management():
    updatePromotionStatus()
    promotions = db.query(QUERY.GET_PROMOTION_LIST.format())
    return render_template('manager/promotion_manage.html', promotions = promotions )

@manager_bp.route('/promotion_management/sort', methods=['POST'])
@level_two_required
def promotion_list_sorted():
    updatePromotionStatus()
    type = request.form.get('type')
    status = request.form.get('status')
    print(type, status)

    typeQ = f'promotion_type = "{type}"' if type else ''
    statusQ = f'status = "{status}"' if status else ''
    andQ = 'AND' if typeQ and statusQ else ''
    
    promotions = db.query(f'SELECT * FROM Promotions WHERE {typeQ} {andQ} {statusQ} ORDER BY promotion_id ASC;')
    return render_template('manager/promotion_manage.html', promotions = promotions, type = type, status = status)


@manager_bp.route('/promotion/<int:id>')
@level_two_required
def promotion_detail(id):
    updatePromotionStatus()
    promotion = db.queryOneResult(QUERY.GET_PROMOTION_DETAIL.format(id))
    categories = db.query(QUERY.GET_PROMOTION_CATAGORIES.format(id))
    subcategories = db.query(QUERY.GET_PROMOTION_SUBCATAGORIES.format(id))

templates/manager/manager_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='manager/img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='manager/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- jQuery CDN -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

  <!-- popper CDN -->
  <script src="https://unpkg.com/@popperjs/core@2"></script>

  <!-- Bootstrap Icons -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='manager/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='manager/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='manager/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='manager/vendor/quill/quill.snow.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='manager/vendor/quill/quill.bubble.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='manager/vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='manager/vendor/simple-datatables/style.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='manager/css/style.css') }}" rel="stylesheet">

  {% block css %}{% endblock %}
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{{ url_for('common.home') }}" class="logo d-flex align-items-center">
        <img src="{{ url_for('static', filename='manager/img/logo.png') }}" alt="">
        <span class="d-none d-lg-block">Manager Dashboard</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="{{ url_for('internal.get_messages_lv1') }}">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-warning badge-number">..</span>
          </a><!-- End Messages Icon -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="/blueprints/static/profile_image/{{session.profile_image}}" alt="Profile" class="rounded-circle" style="width:36px;">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{session.first_name}} {{session.last_name}} </span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{session.first_name}} {{session.last_name}}</h6>
              <span>Manager ID: {{session.user_id}}</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{{ url_for('manager.manager_profile') }}">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{{ url_for('user.logout') }}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.manager_dashboard') }}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li>
        <hr class="dropdown-divider">
      </li>

      <li class="nav-heading">Management</li>

        <li class="nav-item">
          <a class="nav-link collapsed" href="{{url_for('internal.editDiscount')}}">
            <i class="bi bi-currency-dollar"></i>
            <span>Edit Discounts</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link collapsed" href="{{url_for('internal.orderManagement')}}">
            <i class="bi bi-cart-check"></i>
            <span>Order Management</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link collapsed" href="{{url_for('internal.inventory_list', role = 'manager')}}">
            <i class="bi bi-table"></i>
            <span>Product Management</span>
          </a>
        </li>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.manager_users_management') }}">
          <i class="bi bi-people-fill"></i>
          <span>Users Management</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.manager_promotion_management') }}">
          <i class="bi bi-currency-dollar"></i>
          <span>Promotion Management</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.rewardManagement') }}">
          <i class="bi bi-gift"></i>
          <span>Reward Management</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.newsManagement') }}">
          <i class="bi bi-newspaper"></i>
          <span>News Management</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('internal.get_application_messages') }}">
          <i class="bi bi-file-earmark-check"></i>
          <span>Application Management</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.accountholderManagement') }}">
          <i class="bi bi-credit-card"></i>
          <span>Credit Limit Management</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.reviewsManagement') }}">
          <i class="bi bi-stars"></i>
          <span>Review Management</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.paymentManagement') }}">
          <i class="bi bi-currency-exchange"></i>
          <span>Track Payment</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.reports') }}">
          <i class="bi bi-journal-text"></i>
          <span>Reports</span>
        </a>
      </li>

      <li class="nav-heading">Account</li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('manager.manager_profile') }}">
          <i class="bi bi-person"></i>
          <span>My Profile</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('internal.get_messages_lv1') }}">
          <i class="bi bi-envelope"></i><span>My Inbox</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('user.logout') }}">
          <i class="bi bi-box-arrow-right"></i>
          <span>Log Out</span>
        </a>
      </li>

    </ul>

  </aside><!-- End Sidebar-->

  {% block content %}{% endblock %}
  {% block customjs %}{% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright © 2024 <strong><span>Moa Creek Rural Supplies</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      Designed by Group AR2
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='manager/vendor/apexcharts/apexcharts.min.js') }}"></script>
  <script src="{{ url_for('static', filename='manager/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='manager/vendor/chart.js/chart.umd.js') }}"></script>
  <script src="{{ url_for('static', filename='manager/vendor/echarts/echarts.min.js') }}"></script>
  <script src="{{ url_for('static', filename='manager/vendor/quill/quill.js') }}"></script>
  <script src="{{ url_for('static', filename='manager/vendor/simple-datatables/simple-datatables.js') }}"></script>
  <script src="{{ url_for('static', filename='manager/vendor/tinymce/tinymce.min.js') }}"></script>
  <script src="{{ url_for('static', filename='manager/vendor/php-email-form/validate.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='manager/js/main.js') }}"></script>
  {% block js %} {% endblock %}

  <!-- Toasts Container -->
    <div aria-live="polite" aria-atomic="true" class="position-relative">
      <div id="toastContainer" class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 11;">
        <!-- Toasts will be added here dynamically -->
      </div>
  
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var messages = JSON.parse('{{ get_flashed_messages(with_categories=true) | tojson | safe }}');
      var toastContainer = document.getElementById('toastContainer');
    
      messages.forEach(function(message) {
        var category = message[0], content = message[1];
        // Define background classes based on message category
        var bgClass = category === 'success' ? 'bg-success text-white' : 
                      category === 'danger' ? 'bg-danger text-white' : 
                      category === 'warning' ? 'bg-warning' : 
                      'bg-primary text-white'; // Default case
    
        var toastHtml = `
          <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true" data-bs-delay="5000">
            <div class="toast-header">
              <strong class="me-auto">Notification</strong>
              <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
            <div class="toast-body ${bgClass}">
              ${content}
            </div>
          </div>
        `;
    
        toastContainer.insertAdjacentHTML('beforeend', toastHtml);
      });
    
      var toastElList = [].slice.call(document.querySelectorAll('.toast'));
      var toastList = toastElList.map(function(toastEl) {
        return new bootstrap.Toast(toastEl).show();
      });
    });

    function messagePrompter(category, message) {
    var toastContainer = document.getElementById('toastContainerFlash');
  
      var category = category, content = message;
      // Define background classes based on message category
      var bgClass = category === 'success' ? 'bg-success text-white' : 
                    category === 'danger' ? 'bg-danger text-white' : 
                    category === 'warning' ? 'bg-warning' : 
                    'bg-primary text-white'; // Default case
  
      var toastHtml = `
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true" data-bs-delay="5000">
          <div class="toast-header">
            <strong class="me-auto">Notification</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body ${bgClass}">
            ${content}
          </div>
        </div>
      `;
      console.log(content);

      toastContainer.innerHTML = toastHtml;
    
    var toastElList = [].slice.call(document.querySelectorAll('.toast'));
    var toastList = toastElList.map(function(toastEl) {
      return new bootstrap.Toast(toastEl).show();
    });
  };
  

    </script> <!---End toast-->   

</body>
</html>