blueprints/common.py
from flask import Blueprint, flash,render_template,request,redirect, session,url_for, jsonify, current_app
from datetime import datetime, timedelta
import db.queryStrings as QUERY
import db.db as db
from util.util import login_required, checkPassword, uploadImage, changePasswordFunction, allowed_file, updatePromotionStatus, level_one_required, get_price_after_discount
import re
import os
from werkzeug.utils import secure_filename
import uuid


common_bp = Blueprint('common',__name__,template_folder='templates',static_folder='static', static_url_path='/blueprints/static/')

# Home Page
@common_bp.route('/')
@common_bp.route('/home')
def home():
    updatePromotionStatus()

    if 'loggedin' in session:
        if session['user_type'] == 'customer':
            return redirect(url_for('customer.customer_dashboard'))
    #     elif session['user_type'] == 'staff':
    #         return redirect(url_for('staff.staff_dashboard'))
    #     elif session['user_type'] == 'manager':
    #         return redirect(url_for('manager.manager_dashboard'))
    #     elif session['user_type'] == 'admin':
    #         return redirect(url_for('admin.admin_dashboard'))
    categories = db.query(QUERY.GET_ALL_CATEGORIES)
    subcategories = db.query(QUERY.GET_ALL_SUBCATEGORIES)
    promotions = db.query(QUERY.GET_PROMOTION_LIST)

    hot_products = db.query(QUERY.GET_HOT_PRODUCTS)
    news = db.query(QUERY.GET_ALL_NEWS)

    return render_template('home.html',  hot_products=hot_products, promotions=promotions, news=news,  categories = categories,subcategories = subcategories )

@common_bp.route('/<role>/password/update', methods = ['GET', 'POST'])
@login_required
def password_update(role):
    if request.method == 'POST':
        currentPassword = request.form.get('currentPassword')
        newPassword = request.form.get('newPassword')
        reNewPassword = request.form.get('reNewPassword')

        query = QUERY.GET_CURRENT_PASSWORD.format(session['user_id'])
        account = db.queryOneResult(query)

        # Check current password is correct
        if not checkPassword(account['password'], currentPassword, account['salt']):
            flash("The current password does not match.", 'warning')
        # Compare the two new password input
        elif newPassword != reNewPassword:
            flash("The new passwords do not match. Please try again.", 'warning')
        # Check password requirement
        elif not re.match(r'^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*\W).{8,}', newPassword):
            flash("The new password must contain at least 4 types and 8 characters.", 'warning')
        # Update Password
        else:
            password, salt = changePasswordFunction(newPassword)
            db.query(QUERY.UPDATE_PASSWORD.format(password, salt, session['user_id']))
            flash("Password updated.", 'success')

        path = f"{role}.{role}_profile"
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')

@common_bp.route('/<role>/profile/uploader', methods = ['GET', 'POST'])
@login_required
def profile_picture_upload(role):
    if request.method == 'POST':
        if 'image' not in request.files:
            flash('No file selected.')
            path = f"{role}.{role}_profile"
            return redirect(url_for(path))
        file = request.files['image']
        if file.filename == '':
            flash('No file uploaded.')
        elif file and allowed_file(file.filename):
            UPLOAD_FOLDER = 'static/profile_image'
            current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
            filename = secure_filename(file.filename)
            
            index = filename.rfind('.')
            substring = filename[index:]
            filename = uuid.uuid4().hex + substring

            basedir = os.path.abspath(os.path.dirname(__file__))
            filePath = basedir + "/" + UPLOAD_FOLDER
            if not os.path.exists(filePath):
                os.makedirs(filePath)
            file.save(os.path.join(basedir, UPLOAD_FOLDER, filename))

            # change blueprint name style to table name style
            roles = role
    
            if role == "staff": 
                roles = 'Staff'
            elif role == "customer": 
                roles = "Customers"
            elif role == "admin": 
                roles = "Admins"
            elif role == "manager": 
                roles = "Managers"

            db.query(QUERY.SET_PROFILE_IMAGE.format(roles, filename, session['user_id']))
            session['profile_image'] = filename
            flash('Image uploaded.', 'success')
        path = f"{role}.{role}_profile" 
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')

@common_bp.route('/<role>/profile/delete', methods = ['GET', 'POST'])
@login_required
def profile_picture_delete(role):
    if request.method == 'POST':
        query = QUERY.GET_PROFILE_IMAGE_PATH.format(session['user_id'])
        file = db.queryOneResult(query)
        try:
            UPLOAD_FOLDER = 'static/profile_image'
            current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
           

            basedir = os.path.abspath(os.path.dirname(__file__))
            filePath = basedir + "/" + UPLOAD_FOLDER
            if not os.path.exists(filePath):
                os.makedirs(filePath)
         
    
            os.remove(os.path.join(basedir, UPLOAD_FOLDER, file['profile_image']))

            # change blueprint name style to table name style
            roles = role
            if role == "staff": 
                roles = 'Staff'
            elif role == "customer": 
                roles = "Customers"
            elif role == "admin": 
                roles = "Admins"
            elif role == "manager": 
                roles = "Managers"


            db.query(QUERY.DELETE_PROFILE_IMAGE.format(roles, session['user_id']))
            flash("Profile image deleted.", 'success')
        except Exception as e:
            flash(f"Error in deleting files: {e}", 'danger')
        path = f"{role}.{role}_profile" 
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')
    


# Contact us Page
@common_bp.route('/contactus')
def contactUs():
    return render_template('contactUs.html')

blueprints/customer.py
from datetime import datetime, date
from flask import Blueprint, flash,render_template,request,redirect, session,url_for, jsonify
from util.util import customer_required, updatePromotionStatus, get_price_after_discount, sendMessage, generateGiftCard, verifyProductInPromotion
import db.queryStrings as QUERY
import db.db as db
from decimal import Decimal


customer_bp = Blueprint('customer',__name__,template_folder='templates')


# Customer Dashboard
@customer_bp.route('/customer')
@customer_required
def customer_dashboard():
    print('{timestamp} -- customer dashboard request started'.format(timestamp=datetime.utcnow().isoformat()))
    query = QUERY.FIND_A_USER_BY_EMAIL.format(session['email'])
    customer_dict = db.queryOneResult(query)
    customer = list(customer_dict.values())

    updatePromotionStatus()
    
    promotions = db.query(QUERY.GET_PROMOTION_LIST)
    categories = db.query(QUERY.GET_ALL_CATEGORIES)
    subcategories = db.query(QUERY.GET_ALL_SUBCATEGORIES)
    # products = db.query(QUERY.GET_ALL_PRODUCTS)
    # hot_products = db.query(QUERY.GET_HOT_PRODUCTS)
    hot_products = db.query(QUERY.GET_HOT_PRODUCTS)

    # products_images = db.query(QUERY.GET_ALL_PRODUCTS_IMAGES)
    news = db.query(QUERY.GET_ALL_NEWS)
    user_id = session['user_id']
    query = QUERY.GET_ALL_MESSAGES_FROM_LV1.format(user_id)
    cus_messages = db.query(query)
    session['cus_messages'] = cus_messages

    # for i, product in enumerate(products):
    #     discountedPrice = get_price_after_discount(product['product_id'], product['product_price'])
    #     if discountedPrice: 
    #         products[i]['discounted_price'] = discountedPrice
    #     if product['stock_quantity'] >= 80:
    #         hot_products.append(product)
    # for i, product in enumerate(hot_products):
    #     discountedPrice = get_price_after_discount(product['product_id'], product['product_price'])
    #     if discountedPrice: 
    #         hot_products[i]['discounted_price'] = discountedPrice
    print('{timestamp} -- customer dashboard request ended'.format(timestamp=datetime.utcnow().isoformat()))
    return render_template('customer/customer_dashboard.html', hot_products=hot_products,  promotions=promotions, customer=customer, news=news, cus_messages=cus_messages, categories = categories, subcategories = subcategories )

@customer_bp.route('/products', methods = ['GET', 'POST'])

def all_products():
    print('{timestamp} -- customer products page request started'.format(timestamp=datetime.utcnow().isoformat()))
    nav_bar_redirect = True
    updatePromotionStatus()
    if request.method == 'POST':
        search_subcategory = request.form.get('search_subcategory')
        
        search = request.form.get('search')
        searchterm = f"%{search}%"
        if not search_subcategory:
            products = db.query(QUERY.SEARCH_ALL_PRODUCTS_WITH_NAME.format(searchterm))
        else:
            products = db.query(QUERY.SEARCH_ALL_PRODUCTS_WITH_NAME_AND_SUBCATEGORY_ID.format(search_subcategory, searchterm))
    else:
        subcategoryID = request.args.get('subcategory')  
        if subcategoryID:
            products = db.query(QUERY.GET_ALL_PRODUCTS_WITH_SUBCATEGORY_ID.format(subcategoryID))        
        else:
            products = db.query(QUERY.GET_ALL_PRODUCTS)
            nav_bar_redirect = False
    
    categories = db.query(QUERY.GET_ALL_CATEGORIES)
    subcategories = db.query(QUERY.GET_ALL_SUBCATEGORIES)
    
    subcategories_in_promotion = db.query(QUERY.GET_ALL_PROMOTION_SUBCATOGERIES_TO_VERIFY)  
    products_in_promotion = db.query(QUERY.GET_ALL_PROMOTION_PRODUCTS_TO_VERIFY)  
    categories_in_promotion = db.query(QUERY.GET_ALL_PROMOTION_CATOGERIES_TO_VERIFY) 

    for i, product in enumerate(products):
        if verifyProductInPromotion(subcategories_in_promotion, products_in_promotion, categories_in_promotion, product['product_id'], product['subcategory_id']):
            discountedPrice = get_price_after_discount(product['product_id'], product['product_price'], 2)
            if discountedPrice: 
                products[i]['discounted_price'] = discountedPrice
    print('{timestamp} -- customer products page request ended'.format(timestamp=datetime.utcnow().isoformat()))
    return render_template('customer/products.html',products=products, subcategories=subcategories, categories=categories, nav_bar_redirect = nav_bar_redirect )


# Customer Profile
@customer_bp.route('/customer/profile')
@customer_required
def customer_profile():
    query = QUERY.GET_CUSTOMER_PROFILE.format(session['user_id'])
    profile = db.queryOneResult(query)
    cus_messages = session.get('cus_messages', [])


    addresses = db.query(QUERY.GET_USER_ADDRESSES.format(session['user_id']))
    return render_template('customer/customer_profile.html', profile = profile, addresses = addresses, cus_messages=cus_messages)


@customer_bp.route('/customer/profile/edit', methods = ['GET', 'POST'])
@customer_required
def customer_profile_edit():
    firstName = request.form.get('firstName')
    lastName = request.form.get('lastName')
    phone = request.form.get('phone')
    if not firstName or not lastName or not phone:
        flash('Please fill in all of the fields.', 'warning')
        profile = {
            "first_name": firstName,
            "last_name": lastName,
            "phone": phone
        }
    else:
        db.query(QUERY.EDIT_CUSTOMER_PROFILE.format(firstName, lastName, phone ,session['user_id']))
        query = QUERY.GET_CUSTOMER_PROFILE.format(session['user_id'])
        profile = db.queryOneResult(query)
        session['first_name'] = firstName
        session['last_name'] = lastName
        flash('Profile updated sucssesfully.', 'success')
    return render_template('customer/customer_profile.html', profile = profile)

# Customer Monthly Payment
@customer_bp.route('/customer/account_holder')
@customer_required
def customer_account_holder():
    query = QUERY.FIND_A_USER_BY_EMAIL.format(session['email'])
    customer_dict = db.queryOneResult(query)
    customer = list(customer_dict.values())
    cus_messages = session.get('cus_messages', [])

    return render_template('customer/account_holder.html',customer=customer, cus_messages=cus_messages)

# Customer Monthly Payment
@customer_bp.route('/customer/submit_account_holder_application', methods=['POST'])
@customer_required
def submit_account_holder_application():

    monthly_limit = request.form['monthlyLimit']
    user_id = session['user_id']

# Account Information
    legal_entity = request.form.getlist('legalEntity')
    other_entity_details = request.form.get('otherEntityDetails', '').replace("'", "''")
    if 'Other' in legal_entity and other_entity_details:
        legal_entity.remove('Other')
        legal_entity.append(f'Other: {other_entity_details}')
    legal_entity_str = ', '.join(legal_entity)
    
    account_name = request.form.get('accountName', '').replace("'", "''")
    trading_name = request.form.get('tradingName', '').replace("'", "''")
    company_number = request.form.get('companyNumber', '').replace("'", "''")
    gst_number = request.form.get('gstNumber', '').replace("'", "''")
    
    # Postal Address
    postal_number = request.form.get('postalNumber', '').replace("'", "''")
    postal_street = request.form.get('postalStreet', '').replace("'", "''")
    postal_suburb = request.form.get('postalSuburb', '').replace("'", "''")
    postal_city = request.form.get('postalCity', '').replace("'", "''")
    postal_province = request.form.get('postalProvince', '').replace("'", "''")
    postal_postcode = request.form.get('postalPostcode', '').replace("'", "''")
    
    # Residential Address
    residential_number = request.form.get('residentialNumber', '').replace("'", "''")
    residential_street = request.form.get('residentialStreet', '').replace("'", "''")
    residential_suburb = request.form.get('residentialSuburb', '').replace("'", "''")
    residential_city = request.form.get('residentialCity', '').replace("'", "''")
    residential_province = request.form.get('residentialProvince', '').replace("'", "''")
    residential_postcode = request.form.get('residentialPostcode', '').replace("'", "''")
    
    # Delivery Address
    delivery_number = request.form.get('deliveryNumber', '').replace("'", "''")
    delivery_street = request.form.get('deliveryStreet', '').replace("'", "''")
    delivery_suburb = request.form.get('deliverySuburb', '').replace("'", "''")
    delivery_city = request.form.get('deliveryCity', '').replace("'", "''")
    delivery_province = request.form.get('deliveryProvince', '').replace("'", "''")
    delivery_postcode = request.form.get('deliveryPostcode', '').replace("'", "''")
    
    # Primary Contact Information
    primary_contact_name = request.form.get('primaryContactName', '').replace("'", "''")
    primary_contact_relationship = request.form.get('primaryContactRelationship', '').replace("'", "''")
    primary_contact_dob = request.form.get('primaryContactDOB', '').replace("'", "''")
    primary_contact_postal_address = request.form.get('primaryContactPostalAddress', '').replace("'", "''")
    primary_contact_home_phone = request.form.get('primaryContactHomePhone', '').replace("'", "''")
    primary_contact_mobile = request.form.get('primaryContactMobile', '').replace("'", "''")
    primary_contact_email = request.form.get('primaryContactEmail', '').replace("'", "''")
    primary_contact_id = request.form.get('primaryContactID', '').replace("'", "''")
    primary_contact_signature = request.form.get('primaryContactSignature', '').replace("'", "''")
    
    # Additional Contact Information
    additional_contact_name = request.form.get('additionalContactName', '').replace("'", "''")
    additional_contact_relationship = request.form.get('additionalContactRelationship', '').replace("'", "''")
    additional_contact_dob = request.form.get('additionalContactDOB', '').replace("'", "''")

templates/customer/address_detail.html
{% extends 'customer/customer_layout.html' %}
{% block title %}
Moa Creek Rural Supplies - Address Details
{% endblock %}

{% block content %}

<div class="breadcrumbs">
  <div class="container">
      <div class="row">
          <div class="col-12">
              <div class="bread-inner">
                  <ul class="bread-list">
                      <li><a href="{{ url_for('common.home') }}">Home<i class="ti-arrow-right"></i></a></li>
                      <li><a href="{{ url_for('customer.customer_profile') }}">Profile<i class="ti-arrow-right"></i></a></li>
                      <li class="active">Address Details</a></li>
                  </ul>
              </div>
          </div>
      </div>
  </div>
</div>

<section>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">

                {% if address %}
                <form method="POST" action="{{ url_for('customer.edit_address_form') }}">
                    <input type="hidden"  id="address_id" name="address_id" value="{{address.address_id}}">
                    <h2>Edit address</h2>

                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <td class="label">Unit Number</td>
                                <td>
                                    <input type="text" class="form-control addy-unit-number" id="unit_number" name="unit_number" value="{{address.unit_number}}">
                                </td>
                            </tr>
                            <tr>
                                <td class="label">Address Line 1</td>
                                <td>
                                    <input type="search" class="form-control addy-line1" id="address_line_1" name="address_line_1"  auto-complete required value="{{address.address_line1}}">
                                </td>
                            </tr>
                            <tr>
                                <td>Address Line 2</td>
                                <td>
                                    <input type="text" class="form-control addy-line2" id="address_line_2" name="address_line_2" value="{{address.address_line2}}">
                                </td>
                            </tr>
                          
                            <tr>
                                <td>City</td>
                                <td>
                                    <input type="text" class="form-control addy-city" id="city" name="city" value="{{address.city}}">
                                </td>
                            </tr>
                            <tr>
                                <td>Region</td>
                                <td>
                                    <input type="text" class="form-control addy-region" id="region" name="region" value="{{address.region}}">
                                </td>
                            </tr>
                            <tr>
                                <td>Postcode</td>
                                <td>
                                    <input type="text" class="form-control addy-postcode" id="postcode" name="postcode" value="{{address.postcode}}">
                                </td>
                            </tr>
                        </table>
                    </div>

                    <button type="submit" class="btn btn-primary btn-xs" >Edit</button>
                    <a href="{{ url_for('customer.customer_profile') }}" class="btn btn-secondary">Cancel</a>
                </form>


                {% else %}
                <form method="POST" action="{{ url_for('customer.add_new_address_form') }}">
                    <h2>New address</h2>
                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <td class="label">Unit Number</td>
                                <td>
                                    <input type="text" class="form-control addy-unit-number" id="unit_number" name="unit_number">
                                </td>
                            </tr>
                            <tr>
                                <td class="label">Address Line 1</td>
                                <td>
                                    <input type="search" class="form-control addy-line1" id="address_line_1" name="address_line_1" placeholder="Start typing an address.." auto-complete required>
                                </td>
                            </tr>
                            <tr>
                                <td>Address Line 2</td>
                                <td>
                                    <input type="text" class="form-control addy-line2" id="address_line_2" name="address_line_2">
                                </td>
                            </tr>
                           
                            <tr>
                                <td>City</td>
                                <td>
                                    <input type="text" class="form-control addy-city" id="city" name="city">
                                </td>
                            </tr>
                            <tr>
                                <td>Region</td>
                                <td>
                                    <input type="text" class="form-control addy-region" id="region" name="region">
                                </td>
                            </tr>
                            <tr>
                                <td>Postcode</td>
                                <td>
                                    <input type="text" class="form-control addy-postcode" id="postcode" name="postcode">
                                </td>
                            </tr>
                        </table>
                    </div>

                    <button type="submit" class="btn btn-primary btn-xs" >Add</button>
                    <a href="{{ url_for('customer.customer_profile') }}" class="btn btn-secondary">Cancel</a>
                </form>
                {% endif %}

            </div>
        </div>
    </div>
</section>

<script src="https://www.addysolutions.com/address-lookup/1.6.2/js/addy.min.js?nzKey=aaa15576a30145c4814596d8b6300363&country=nz&loadcss=true" async defer></script>

{% endblock %}

templates/customer/promotion_products.html
{% extends 'customer/customer_layout.html' %} 
{% block title %} Moa Creek Rural Supplies Customer {% endblock %}
{% block content %}

{% block css %}
<!-- Jquery Ui -->
<link rel="stylesheet" href="{{ url_for('static', filename='customer/css/jquery-ui.css') }}">
{% endblock %}
	
<!-- Breadcrumbs -->
<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="bread-inner">
					<ul class="bread-list">
						<li><a href="{{ url_for('common.home') }}">Home<i class="ti-arrow-right"></i></a></li>
						<li><a href="{{ url_for('customer.all_products') }}">Products<i class="ti-arrow-right"></i></a></li>
						<li class="active">Current Promotion Products</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Breadcrumbs -->
    <!-- Start Body Area -->
		<!-- Slider Area -->
        <section class="hero-slider" style="max-height: 400px; overflow: hidden;">
			<!-- Single Slider -->
			<div class="single-slider">
				<div class="container-fluid">			
					<!-- Carousel -->
					<div id="demo" class="carousel slide" data-bs-ride="carousel">
						<!-- Indicators/dots -->
						<div class="carousel-indicators">
							<button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
							{% for promotion in promotions %}
							<button type="button" data-bs-target="#demo" data-bs-slide-to="{{ loop.index }}"></button>
							{% endfor %}
						</div>
		
						<!-- The slideshow/carousel -->
						<div class="carousel-inner">
							<div class="carousel-item active">
								<img src="/static/promotion_image/New Zealand's Rural Excellence.jpeg" alt="promotion_image" class="d-block w-100" loading="lazy" style="max-height: 400px; object-fit: cover;">
								<div class="carousel-caption" style="bottom: 20px;">
									<div class="hero-text">
										<h1><span>UP TO 50% OFF </span>New Zealand's Rural Excellence</h1>
										<p>Visit our website to explore <br> our full range of premium<br> rural agricultural products. </p>
										<div class="button">
											<a href="{{ url_for('customer.customer_promotions') }}" class="btn">Shop Now!</a>
										</div>
									</div>
								</div>
							</div>
							{% for promotion in promotions %}
							<div class="carousel-item">
								<img src="/static/promotion_image/{{promotion.promotion_image}}" alt="{{promotion.promotion_name}}" class="d-block w-100" loading="lazy" style="max-height: 400px; object-fit: cover;">
								<div class="carousel-caption" style="bottom: 20px;">
									<div class="hero-text">
										<h1><span>UP TO 50% OFF </span>{{promotion.promotion_name}}</h1>
										{% set words = promotion.promotion_description.split() %}
										<p>{{ ' '.join(words[:3]) }} <br> {{ ' '.join(words[3:]) }} </p>
										{% if promotion.status != 'Active' %}
                                        <p style="color: orange;">Coming Soon </p>
                                        {%endif%}
										<div class="button">
											<a href="{{ url_for('customer.customer_promotions') }}" class="btn">Shop Now!</a>
										</div>
									</div>
								</div>
							</div>
							{% endfor %}
						</div>
					
						<!-- Left and right controls/icons -->
						<button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
							<span class="carousel-control-prev-icon" style="background-color: rgba(0,0,0,0.5); border-radius: 50%;"></span>
						</button>
						<button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
							<span class="carousel-control-next-icon" style="background-color: rgba(0,0,0,0.5); border-radius: 50%;"></span>
						</button>
					</div>
				</div>					
			</div>
			<!--/ End Single Slider -->
		</section>
		
	<!-- Start Product Area -->
	<div class="product-area section" id="products">
		<div class="container-md">
			<div class="row">
				<div class="col-12">
					<div class="section-title">
						<h2>Current Promotion Products</h2>
						<p style="color: red;">* All our products prices are GST inclusive<br> Contact us for NZ outer islands delivery</p>							
					</div>						
				</div>
			</div>
			<div class="row">
				<div class="col-12">
					<div class="product-info">
						
						<div class="tab-content" id="myTabContent">
							<!-- Start Single Tab -->
							<div class="tab-pane fade show active" id="all" role="tabpanel">
								<div class="tab-single">
									<div class="row">
										{% for product in products %}
										<div class="col-xl-3 col-lg-4 col-md-4 col-12">
											<div class="single-product">
												<div class="product-img">
													<a href="{{ url_for('customer.customer_products', id=product.product_id) }}">
														
														{% if product.product_image_id %}
														<img class="default-img" src="/blueprints/static/product_image/{{product.product_image}}" alt="{{product.product_image}}" loading="lazy">

														<span class="special-icon">Special</span>
														{% else %}
														
														<img class="default-img" src="/blueprints/static/product_image/default-image.jpg" alt="{{default-image.jpg}}" loading="lazy">
														<span class="special-icon">Special</span>

														{% endif %}
												
													</a>
													<div class="button-head">
														<div class="product-action-2">
															<a title="Add to cart" onclick="addToCart('{{product.product_name}}',{{product.product_id}}, 1)">Add to cart</a>
														</div>
													</div>
												</div>
												<div class="product-content">
													<h3><a href="{{ url_for('customer.customer_products', id=product.product_id) }}">{{product.product_name}}</a></h3>
													<div class="product-price">
														{% if product.discounted_price == "buyOneGetOneFree" %}
														<span class="text-decoration-line-through">${{product.product_price}}</span>
														<h5 class="text-danger">Buy One Get One FREE</h5>
														{% elif product.discounted_price %}
														<span class="text-decoration-line-through">${{product.product_price}}</span>
														<h3 class="text-danger">${{product.discounted_price}}</h3>
														{% else %}
														<span>${{product.product_price}}</span>
														{% endif %}
														
													</div>
													
												</div>
											</div>
										</div>
										{% endfor %}
									</div>
								</div>
							</div>
							<!--/ End Single Tab -->
							<!-- Start Single Tab -->
							{% for subcategory in subcategories %}
							<div class="tab-pane fade" id="{{subcategory.subcategory_id}}" role="tabpanel">
								<div class="tab-single">
									<div class="row">
										{% for product in products %}
										{% if subcategory.subcategory_id == product.subcategory_id %}
										<div class="col-xl-3 col-lg-4 col-md-4 col-12">
											<div class="single-product">
												<div class="product-img">
													<a href="{{ url_for('customer.customer_products', id=product.product_id) }}">
														{% if product.product_image_id %}
														<img class="default-img" src="/blueprints/static/product_image/{{product.product_image}}" alt="{{product.product_image}}" loading="lazy">
														{% else %}
														<img class="default-img" src="/blueprints/static/product_image/default-image.jpg" alt="{{default-image.jpg}}" loading="lazy">												
														{% endif %}
													</a>
													<div class="button-head">
													
														<div class="product-action-2">
															<a title="Add to cart" onclick="addToCart('{{product.product_name}}',{{product.product_id}}, 1)">Add to cart</a>
														</div>
													</div>
												</div>
												<div class="product-content">
													<h3><a href="{{ url_for('customer.customer_products', id=product.product_id) }}">{{product.product_name}}</a></h3>
													<div class="product-price">
														{% if product.discounted_price %}
														<span class="text-decoration-line-through">${{product.product_price}}</span>
														<h3 class="text-danger">${{product.discounted_price}}</h3>
														{% else %}
														<span>${{product.product_price}}</span>
														{% endif %}
														
													</div>
												
												</div>
											</div>
										</div>
										{% endif %}
										{% endfor %}		
									</div>
								</div>
							</div>
							{% endfor %}
							<!--/ End Single Tab -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<!-- End Product Area -->
<script>


</script>
	
{% block js %} 
<!-- Fancybox JS -->
<script src="{{ url_for('static', filename='customer/js/facnybox.min.js') }}"></script>
<!-- Ytplayer JS -->
<script src="{{ url_for('static', filename='customer/js/ytplayer.min.js') }}"></script>

{% endblock%}

{% endblock %}