blueprints/common.py
from flask import Blueprint, flash,render_template,request,redirect, session,url_for, jsonify, current_app
from datetime import datetime, timedelta
import db.queryStrings as QUERY
import db.db as db
from util.util import login_required, checkPassword, uploadImage, changePasswordFunction, allowed_file, updatePromotionStatus, level_one_required, get_price_after_discount
import re
import os
from werkzeug.utils import secure_filename
import uuid


common_bp = Blueprint('common',__name__,template_folder='templates',static_folder='static', static_url_path='/blueprints/static/')

# Home Page
@common_bp.route('/')
@common_bp.route('/home')
def home():
    updatePromotionStatus()

    if 'loggedin' in session:
        if session['user_type'] == 'customer':
            return redirect(url_for('customer.customer_dashboard'))
    #     elif session['user_type'] == 'staff':
    #         return redirect(url_for('staff.staff_dashboard'))
    #     elif session['user_type'] == 'manager':
    #         return redirect(url_for('manager.manager_dashboard'))
    #     elif session['user_type'] == 'admin':
    #         return redirect(url_for('admin.admin_dashboard'))
    categories = db.query(QUERY.GET_ALL_CATEGORIES)
    subcategories = db.query(QUERY.GET_ALL_SUBCATEGORIES)
    promotions = db.query(QUERY.GET_PROMOTION_LIST)

    hot_products = db.query(QUERY.GET_HOT_PRODUCTS)
    news = db.query(QUERY.GET_ALL_NEWS)

    return render_template('home.html',  hot_products=hot_products, promotions=promotions, news=news,  categories = categories,subcategories = subcategories )

@common_bp.route('/<role>/password/update', methods = ['GET', 'POST'])
@login_required
def password_update(role):
    if request.method == 'POST':
        currentPassword = request.form.get('currentPassword')
        newPassword = request.form.get('newPassword')
        reNewPassword = request.form.get('reNewPassword')

        query = QUERY.GET_CURRENT_PASSWORD.format(session['user_id'])
        account = db.queryOneResult(query)

        # Check current password is correct
        if not checkPassword(account['password'], currentPassword, account['salt']):
            flash("The current password does not match.", 'warning')
        # Compare the two new password input
        elif newPassword != reNewPassword:
            flash("The new passwords do not match. Please try again.", 'warning')
        # Check password requirement
        elif not re.match(r'^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*\W).{8,}', newPassword):
            flash("The new password must contain at least 4 types and 8 characters.", 'warning')
        # Update Password
        else:
            password, salt = changePasswordFunction(newPassword)
            db.query(QUERY.UPDATE_PASSWORD.format(password, salt, session['user_id']))
            flash("Password updated.", 'success')

        path = f"{role}.{role}_profile"
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')

@common_bp.route('/<role>/profile/uploader', methods = ['GET', 'POST'])
@login_required
def profile_picture_upload(role):
    if request.method == 'POST':
        if 'image' not in request.files:
            flash('No file selected.')
            path = f"{role}.{role}_profile"
            return redirect(url_for(path))
        file = request.files['image']
        if file.filename == '':
            flash('No file uploaded.')
        elif file and allowed_file(file.filename):
            UPLOAD_FOLDER = 'static/profile_image'
            current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
            filename = secure_filename(file.filename)
            
            index = filename.rfind('.')
            substring = filename[index:]
            filename = uuid.uuid4().hex + substring

            basedir = os.path.abspath(os.path.dirname(__file__))
            filePath = basedir + "/" + UPLOAD_FOLDER
            if not os.path.exists(filePath):
                os.makedirs(filePath)
            file.save(os.path.join(basedir, UPLOAD_FOLDER, filename))

            # change blueprint name style to table name style
            roles = role
    
            if role == "staff": 
                roles = 'Staff'
            elif role == "customer": 
                roles = "Customers"
            elif role == "admin": 
                roles = "Admins"
            elif role == "manager": 
                roles = "Managers"

            db.query(QUERY.SET_PROFILE_IMAGE.format(roles, filename, session['user_id']))
            session['profile_image'] = filename
            flash('Image uploaded.', 'success')
        path = f"{role}.{role}_profile" 
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')

@common_bp.route('/<role>/profile/delete', methods = ['GET', 'POST'])
@login_required
def profile_picture_delete(role):
    if request.method == 'POST':
        query = QUERY.GET_PROFILE_IMAGE_PATH.format(session['user_id'])
        file = db.queryOneResult(query)
        try:
            UPLOAD_FOLDER = 'static/profile_image'
            current_app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
           

            basedir = os.path.abspath(os.path.dirname(__file__))
            filePath = basedir + "/" + UPLOAD_FOLDER
            if not os.path.exists(filePath):
                os.makedirs(filePath)
         
    
            os.remove(os.path.join(basedir, UPLOAD_FOLDER, file['profile_image']))

            # change blueprint name style to table name style
            roles = role
            if role == "staff": 
                roles = 'Staff'
            elif role == "customer": 
                roles = "Customers"
            elif role == "admin": 
                roles = "Admins"
            elif role == "manager": 
                roles = "Managers"


            db.query(QUERY.DELETE_PROFILE_IMAGE.format(roles, session['user_id']))
            flash("Profile image deleted.", 'success')
        except Exception as e:
            flash(f"Error in deleting files: {e}", 'danger')
        path = f"{role}.{role}_profile" 
        return redirect(url_for(path))
    else:
        flash("400 Bad request.", "danger")
        return redirect('/')
    


# Contact us Page
@common_bp.route('/contactus')
def contactUs():
    return render_template('contactUs.html')

blueprints/staff.py
from flask import Blueprint, flash, render_template, session, request
from util.util import login_required, staff_required
import db.queryStrings as QUERY
import db.db as db


staff_bp = Blueprint('staff',__name__,template_folder='templates')


# Staff Dashboard
@staff_bp.route('/staff')
@staff_required
def staff_dashboard():

    query = QUERY.FIND_A_STAFF_BY_ID.format(session['user_id'])
    staff_dict = db.queryOneResult(query)
    staff = list(staff_dict.values())
    product_count = db.queryOneResult(QUERY.PRODUCT_COUNT)['count(product_id)']
    active_product_count = db.queryOneResult(QUERY.ACTIVE_PRODUCT_COUNT)['count(product_id)']
    inactive_product_count = db.queryOneResult(QUERY.INACTIVE_PRODUCT_COUNT)['count(product_id)']
    this_month_order_count = db.queryOneResult(QUERY.CURRENT_MONTH_ORDERS_COUNT)['current_month_orders']
    last_month_order_count = db.queryOneResult(QUERY.LAST_MONTH_ORDERS_COUNT)['previous_month_orders']
    new_message_count = db.queryOneResult(QUERY.NEW_MESSAGE_COUNT)['count(message_id)']
    orders = db.query(QUERY.GET_ALL_ORDERS)

    return render_template('staff/staff_dashboard.html', staff=staff, product_count=product_count,active_product_count=active_product_count, inactive_product_count=inactive_product_count, 
                           this_month_order_count=this_month_order_count, last_month_order_count=last_month_order_count, new_message_count=new_message_count, orders = orders)

# Staff Profile
@staff_bp.route('/staff/profile')
@staff_required
def staff_profile():
    query = QUERY.GET_STAFF_PROFILE.format(session['user_id'])
    profile = db.queryOneResult(query)
    return render_template('staff/staff_profile.html', profile = profile)

@staff_bp.route('/staff/profile/edit', methods = ['GET', 'POST'])
@staff_required
def staff_profile_edit():
    firstName = request.form.get('firstName')
    lastName = request.form.get('lastName')
    phone = request.form.get('phone')
    if not firstName or not lastName or not phone:
        flash('Please fill in all of the fields.', 'warning')
        profile = {
            "first_name": firstName,
            "last_name": lastName,
            "phone": phone
        }
    else:
        db.query(QUERY.EDIT_STAFF_PROFILE.format(firstName, lastName, phone ,session['user_id']))
        query = QUERY.GET_STAFF_PROFILE.format(session['user_id'])
        profile = db.queryOneResult(query)
        session['first_name'] = firstName
        session['last_name'] = lastName
        flash('Profile updated sucssesfully.', 'success')
    return render_template('staff/staff_profile.html', profile = profile)

templates/staff/staff_layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{ url_for('static', filename='staff/img/favicon.png') }}" rel="icon">
  <link href="{{ url_for('static', filename='staff/img/apple-touch-icon.png') }}" rel="apple-touch-icon">

  <!-- jQuery CDN -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{ url_for('static', filename='staff/vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='staff/vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='staff/vendor/boxicons/css/boxicons.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='staff/vendor/quill/quill.snow.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='staff/vendor/quill/quill.bubble.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='staff/vendor/remixicon/remixicon.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='staff/vendor/simple-datatables/style.css') }}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{ url_for('static', filename='staff/css/style.css') }}" rel="stylesheet">

  {% block css %}{% endblock %}
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{{ url_for('common.home') }}" class="logo d-flex align-items-center">
        <img src="{{ url_for('static', filename='staff/img/logo.png') }}" alt="">
        <span class="d-none d-lg-block">Staff Dashboard</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="{{ url_for('internal.get_messages_lv1') }}">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-warning badge-number">..</span>
          </a><!-- End Messages Icon -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="/blueprints/static/profile_image/{{session.profile_image}}" alt="Profile" class="rounded-circle" style="width:36px;">
            <span class="d-none d-md-block dropdown-toggle ps-2">{{session.first_name}} {{session.last_name}} </span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{session.first_name}} {{session.last_name}}</h6>
              <span>Staff ID: {{session.user_id}}</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{{ url_for('staff.staff_profile') }}">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="{{ url_for('user.logout') }}">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('staff.staff_dashboard') }}">
          <i class="bi bi-grid"></i>
          <span>Dashboard</span>
        </a>
      </li>
      <li>
        <hr class="dropdown-divider">
      </li>
      <li class="nav-heading">Management</li>
    

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{url_for('internal.editDiscount')}}">
          <i class="bi bi-currency-dollar"></i><span>Edit Discounts</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('internal.orderManagement') }}">
          <i class="bi bi-cart-check"></i><span>Order Management</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed"  href="{{url_for('internal.inventory_list', role = 'staff')}}">
          <i class="bi bi-table"></i><span>Product Management</span>
        </a>
      </li>

      <li class="nav-heading">Account</li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('staff.staff_profile') }}">
          <i class="bi bi-person"></i>
          <span>My Profile</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#components-nav" href="{{ url_for('internal.get_messages_lv1') }}">
          <i class="bi bi-envelope"></i><span>My Inbox</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="{{ url_for('user.logout') }}">
          <i class="bi bi-box-arrow-right"></i>
          <span>Log Out</span>
        </a>
      </li>

    </ul>

  </aside><!-- End Sidebar-->

  {% block content %}{% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright © 2024 <strong><span>Moa Creek Rural Supplies</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      Designed by Group AR2
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{ url_for('static', filename='staff/vendor/apexcharts/apexcharts.min.js') }}"></script>
  <script src="{{ url_for('static', filename='staff/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
  <script src="{{ url_for('static', filename='staff/vendor/chart.js/chart.umd.js') }}"></script>
  <script src="{{ url_for('static', filename='staff/vendor/echarts/echarts.min.js') }}"></script>
  <script src="{{ url_for('static', filename='staff/vendor/quill/quill.js') }}"></script>
  <script src="{{ url_for('static', filename='staff/vendor/simple-datatables/simple-datatables.js') }}"></script>
  <script src="{{ url_for('static', filename='staff/vendor/tinymce/tinymce.min.js') }}"></script>
  <script src="{{ url_for('static', filename='staff/vendor/php-email-form/validate.js') }}"></script>

  <!-- Template Main JS File -->
  <script src="{{ url_for('static', filename='staff/js/main.js') }}"></script>
  <!-- Toasts Container -->
  <div aria-live="polite" aria-atomic="true" class="position-relative">
    <div id="toastContainer" class="toast-container position-fixed bottom-0 end-0 p-3" style="z-index: 11;">
      <!-- Toasts will be added here dynamically -->
    </div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var messages = JSON.parse('{{ get_flashed_messages(with_categories=true) | tojson | safe }}');
    var toastContainer = document.getElementById('toastContainer');
  
    messages.forEach(function(message) {
      var category = message[0], content = message[1];
      // Define background classes based on message category
      var bgClass = category === 'success' ? 'bg-success text-white' : 
                    category === 'danger' ? 'bg-danger text-white' : 
                    category === 'warning' ? 'bg-warning' : 
                    'bg-primary text-white'; // Default case
  
      var toastHtml = `
        <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-bs-autohide="true" data-bs-delay="5000">
          <div class="toast-header">
            <strong class="me-auto">Notification</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body ${bgClass}">
            ${content}
          </div>
        </div>
      `;
  
      toastContainer.insertAdjacentHTML('beforeend', toastHtml);
    });
  
    var toastElList = [].slice.call(document.querySelectorAll('.toast'));
    var toastList = toastElList.map(function(toastEl) {
      return new bootstrap.Toast(toastEl).show();
    });
  });
  </script> <!---End toast-->   

  {% block js %} {% endblock %}
</body>

</html>

templates/staff/staff_profile.html
{% extends 'staff/staff_layout.html' %} 
{% block title %} Moa Creek Rural Supplies Staff {% endblock %}
{% block content %}

<main id="main" class="main">

    <div class="pagetitle">
      <h1>Staff Profile</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{{ url_for('staff.staff_dashboard') }}">Home</a></li>
          <li class="breadcrumb-item active">Profile</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section profile">
      <div class="row">
        <div class="col-xl-4">
  
          <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
            
              <img src="/blueprints/static/profile_image/{{profile.profile_image}}" alt="Profile" class="">
              <h2>{{profile.first_name}} {{profile.last_name}}</h2>
              <h3>Staff</h3>
            </div>
          </div>
  
        </div>
  
        <div class="col-xl-8">
  
          <div class="card">
            <div class="card-body pt-3">
              <!-- Bordered Tabs -->
              <ul class="nav nav-tabs nav-tabs-bordered">
  
                <li class="nav-item">
                  <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#profile-overview">Overview</button>
                </li>
  
                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">Edit Profile</button>
                </li>
  
                <li class="nav-item">
                  <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-change-password">Change Password</button>
                </li>
  
              </ul>
              <div class="tab-content pt-2">
  
                <div class="tab-pane fade show active profile-overview" id="profile-overview">
  
                  <h5 class="card-title">Profile Details</h5>
  
                  <div class="row">
                    <div class="col-lg-3 col-md-4 label ">Full Name</div>
                    <div class="col-lg-9 col-md-8">{{profile.first_name}} {{profile.last_name}} </div>
                  </div>
  
                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Phone</div>
                    <div class="col-lg-9 col-md-8">{{profile.phone}}</div>
                  </div>
  
                  <div class="row">
                    <div class="col-lg-3 col-md-4 label">Email</div>
                    <div class="col-lg-9 col-md-8">{{profile.email_address}}</div>
                  </div>
  
                </div>
  
                <div class="tab-pane fade profile-edit pt-3" id="profile-edit">
  
                  <!-- Profile Edit Form -->
                  <div class="row mb-3">
                    <label for="profileImage" class="col-md-4 col-lg-3 col-form-label">Profile Image</label>
                    <div class="col-md-8 col-lg-9">
                      <img src="/blueprints/static/profile_image/{{profile.profile_image}}" alt="Profile">
                      <div class="pt-2 row">
                        <form action="profile/uploader" method="post" enctype="multipart/form-data" class="pt-2 col-md-1">
                          <input type="file" name="image" id="image" style="display: none;" onchange="form.submit()">
                          <label for="image" class="btn btn-primary btn-sm" title="Upload new profile image"><i class="bi bi-upload"></i></label>
                        </form>
                    
                        {% if profile.profile_image != 'default-image.jpg'%}
                   
                        <form action="profile/delete" method="post" enctype="multipart/form-data" class="pt-2 col-md-1">
                          <button type="submit" class="btn btn-danger btn-sm" title="Remove my profile image"><i class="bi bi-trash"></i></button>
                        </form>
                        {% endif %}
                      </div>
                    </div>
                  </div>
  
                  <form method="POST" action="{{ url_for('staff.staff_profile_edit') }}">
                    <div class="row mb-3">
                      <label for="firstName" class="col-md-4 col-lg-3 col-form-label">First Name</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="firstName" type="text" class="form-control" id="firstName" value="{{profile.first_name}}" required>
                      </div>
                    </div>
  
                    <div class="row mb-3">
                      <label for="lastName" class="col-md-4 col-lg-3 col-form-label">Last Name</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="lastName" type="text" class="form-control" id="lastName" value="{{profile.last_name}}" required>
                      </div>
                    </div>
  
                    <div class="row mb-3">
                      <label for="Phone" class="col-md-4 col-lg-3 col-form-label">Phone</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="phone" type="text" class="form-control" id="Phone" value="{{profile.phone}}" required>
                      </div>
                    </div>
  
                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form><!-- End Profile Edit Form -->
  
                </div>
  
                <div class="tab-pane fade pt-3" id="profile-change-password">
                  <!-- Change Password Form -->
                  <form method="POST" action="{{ url_for('common.password_update', role = 'staff') }}">
  
                    <div class="row mb-3">
                      <label for="currentPassword" class="col-md-4 col-lg-3 col-form-label">Current Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="currentPassword" type="password" class="form-control" id="currentPassword" required>
                      </div>
                    </div>
  
                    <div class="row mb-3">
                      <label for="newPassword" class="col-md-4 col-lg-3 col-form-label">New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="newPassword" type="password" class="form-control" id="newPassword" required>
                      </div>
                    </div>
  
                    <div class="row mb-3">
                      <label for="reNewPassword" class="col-md-4 col-lg-3 col-form-label">Re-enter New Password</label>
                      <div class="col-md-8 col-lg-9">
                        <input name="reNewPassword" type="password" class="form-control" id="reNewPassword" required>
                      </div>
                    </div>
  
                    <div class="text-center">
                      <button type="submit" class="btn btn-primary">Change Password</button>
                    </div>
                  </form><!-- End Change Password Form -->
  
                </div>
  
              </div><!-- End Bordered Tabs -->
  
            </div>
          </div>
  
        </div>
      </div>
    </section>
</main><!-- End #main -->


{% endblock %}